require_relative("lib/fizz_buzzer.rb")
fizz_buzz = FizzBuzzer.new
puts ""
puts "Output == 7"
p fizz_buzz.replace_number(7) == "7"
puts ""
puts "Output == 11"
p fizz_buzz.replace_number(11) == "11"
puts ""
puts "Output == Fizz, Input == 9"
p fizz_buzz.replace_number(9) == "Fizz"
puts ""
puts "Output == Fizz, Input == 12"
p fizz_buzz.replace_number(12) == "Fizz"
puts ""
puts "Output == Buzz, Input == 10"
p fizz_buzz.replace_number(10) == "Buzz"
puts ""
puts "Output == Buzz, Input == 20"
p fizz_buzz.replace_number(25) == "Buzz"
puts ""
puts "Output == FizzBuzz, Input == 15"
p fizz_buzz.replace_number(15) == "FizzBuzz"
puts ""
puts "Output == FizzBuzz, Input == 30"
p fizz_buzz.replace_number(30) == "FizzBuzz"
puts ""