# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d53fce3d3ebd36de054731b8132a25c4c4a650f52ffb1ede7defdfd99fea57056f125981f89c14f95eee4b72482fc39efc3b10f34c7fd837966d7af93536bb3c

test:
  secret_key_base: e3b0fdf0a55b07b243820ad11b7ce3cde0683165e58b645a0cec3ae197abbd28332de31f95dba24c4ca6246925392630dd0b8df3534aab0106814010e6f9a919

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
